In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
training=pd.read_csv("pune_historical_weather_data.csv")
testing=pd.read_csv("pune.csv")

In [3]:
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              974 non-null    object 
 1   datetime          974 non-null    object 
 2   tempmax           974 non-null    float64
 3   tempmin           974 non-null    float64
 4   temp              974 non-null    float64
 5   feelslikemax      974 non-null    float64
 6   feelslikemin      974 non-null    float64
 7   feelslike         974 non-null    float64
 8   dew               974 non-null    float64
 9   humidity          974 non-null    float64
 10  precip            974 non-null    float64
 11  precipprob        974 non-null    float64
 12  precipcover       974 non-null    float64
 13  preciptype        472 non-null    object 
 14  snow              600 non-null    float64
 15  snowdepth         600 non-null    float64
 16  windgust          600 non-null    float64
 1

In [4]:
testing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              15 non-null     object 
 1   datetime          15 non-null     object 
 2   tempmax           15 non-null     float64
 3   tempmin           15 non-null     float64
 4   temp              15 non-null     float64
 5   feelslikemax      15 non-null     float64
 6   feelslikemin      15 non-null     float64
 7   feelslike         15 non-null     float64
 8   dew               15 non-null     float64
 9   humidity          15 non-null     float64
 10  precip            15 non-null     float64
 11  precipprob        15 non-null     float64
 12  precipcover       15 non-null     float64
 13  preciptype        15 non-null     object 
 14  snow              15 non-null     int64  
 15  snowdepth         15 non-null     int64  
 16  windgust          15 non-null     float64
 17 

In [5]:
training.columns==testing.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [6]:
features_to_drop = ['name',
                    'solarenergy',
                    "precipprob",
                    "precipcover",
                    "preciptype",
                    "snow",
                    "snowdepth",
                    "windgust",
                    'winddir',
                    'sealevelpressure',
                    'visibility',
                    'solarradiation',
                    'solarenergy',
                    'uvindex',
                    'severerisk',
                    'sunrise',
                    'sunset',
                    'moonphase',
                    'description',
                    'icon',
                    'stations',
                    'datetime']

In [7]:
training.drop(features_to_drop,axis=1,inplace=True)
testing.drop(features_to_drop,axis=1,inplace=True)

In [8]:
training

tempmax  tempmin  temp  feelslikemax  feelslikemin  feelslike   dew  \
0       85.3     60.9  71.2          86.7          60.9       71.6  63.1   
1       83.9     63.6  71.6          84.0          63.6       71.6  63.2   
2       83.0     60.5  70.5          82.6          60.5       70.5  60.4   
3       80.3     63.2  70.7          81.4          63.2       70.8  63.2   
4       80.8     62.5  71.1          82.9          62.5       71.3  63.9   
..       ...      ...   ...           ...           ...        ...   ...   
969     77.1     68.8  72.1          77.1          68.8       72.1  67.6   
970     78.7     69.5  72.8          78.7          69.5       72.8  67.7   
971     80.3     68.4  73.4          82.9          68.4       73.6  67.3   
972     81.6     68.6  74.2          84.4          68.6       74.7  67.3   
973     80.7     67.9  73.7          83.3          67.9       74.0  67.5   

     humidity  precip  windspeed  cloudcover              conditions  
0        77.3   0.000       11.0        70.3        Partially cloudy  
1        76.7   0.000        8.9        69.6        Partially cloudy  
2        73.3   0.000        9.4        60.4        Partially cloudy  
3        78.7   0.036       10.1        60.2  Rain, Partially cloudy  
4        79.1   0.004        8.3        86.3  Rain, Partially cloudy  
..        ...     ...        ...         ...                     ...  
969      86.0   0.028       13.6        90.4                Overcast  
970      84.7   0.032       14.1        65.1        Partially cloudy  
971      82.0   0.028       11.0        78.4        Partially cloudy  
972      79.9   0.024       10.5        94.4          Rain, Overcast  
973      81.9   0.012       10.1        93.0                Overcast  

[974 rows x 12 columns]

In [9]:
testing

tempmax  tempmin  temp  feelslikemax  feelslikemin  feelslike   dew  \
0      81.2     68.8  73.4          84.3          68.8       73.8  67.7   
1      79.6     69.0  73.1          79.6          69.0       73.1  67.7   
2      77.4     69.9  72.4          77.4          69.9       72.4  67.9   
3      79.4     69.0  73.0          79.4          69.0       73.0  67.0   
4      80.5     67.7  73.0          83.2          67.7       73.2  67.0   
5      80.0     69.0  73.1          80.0          69.0       73.1  67.4   
6      78.5     68.8  72.5          78.5          68.8       72.5  67.0   
7      80.5     68.4  73.3          83.2          68.4       73.5  67.2   
8      81.4     68.3  73.8          84.0          68.3       74.3  67.0   
9      77.1     68.1  72.3          77.1          68.1       72.3  66.7   
10     80.9     67.4  73.3          83.1          67.4       73.6  66.2   
11     81.4     67.7  73.3          84.1          67.7       73.7  66.8   
12     77.8     67.6  72.1          77.8          67.6       72.1  66.8   
13     81.1     67.2  73.2          83.9          67.2       73.6  67.3   
14     81.6     68.3  73.9          84.9          68.3       74.4  68.0   

    humidity  precip  windspeed  cloudcover              conditions  
0       83.0   0.020       14.5        77.8  Rain, Partially cloudy  
1       83.8   0.024       15.7        71.2        Partially cloudy  
2       86.0   0.024       13.0        84.3  Rain, Partially cloudy  
3       82.2   0.008       14.8        59.7  Rain, Partially cloudy  
4       82.5   0.016       14.5        40.9  Rain, Partially cloudy  
5       83.1   0.028       14.1        42.0        Partially cloudy  
6       83.5   0.036       13.4        38.5        Partially cloudy  
7       82.0   0.036       12.8        50.3        Partially cloudy  
8       80.3   0.024       13.4        65.8        Partially cloudy  
9       83.1   0.012       11.2        92.5                Overcast  
10      79.6   0.020       11.9        24.4        Partially cloudy  
11      81.2   0.024       13.4        47.2        Partially cloudy  
12      83.8   0.004       10.5        89.9        Partially cloudy  
13      82.9   0.016       13.2        72.2        Partially cloudy  
14      83.1   0.047       13.2        66.7        Partially cloudy

In [10]:
rep_vals = {
    "Rain, Partially cloudy": "rainpartlycloudy",
    "Rain, Overcast": "rainovercast",

}
training["conditions"]=training["conditions"].replace(list(rep_vals.keys()),list(rep_vals.values()))
testing["conditions"]=testing["conditions"].replace(list(rep_vals.keys()),list(rep_vals.values()))

In [11]:
training

tempmax  tempmin  temp  feelslikemax  feelslikemin  feelslike   dew  \
0       85.3     60.9  71.2          86.7          60.9       71.6  63.1   
1       83.9     63.6  71.6          84.0          63.6       71.6  63.2   
2       83.0     60.5  70.5          82.6          60.5       70.5  60.4   
3       80.3     63.2  70.7          81.4          63.2       70.8  63.2   
4       80.8     62.5  71.1          82.9          62.5       71.3  63.9   
..       ...      ...   ...           ...           ...        ...   ...   
969     77.1     68.8  72.1          77.1          68.8       72.1  67.6   
970     78.7     69.5  72.8          78.7          69.5       72.8  67.7   
971     80.3     68.4  73.4          82.9          68.4       73.6  67.3   
972     81.6     68.6  74.2          84.4          68.6       74.7  67.3   
973     80.7     67.9  73.7          83.3          67.9       74.0  67.5   

     humidity  precip  windspeed  cloudcover        conditions  
0        77.3   0.000       11.0        70.3  Partially cloudy  
1        76.7   0.000        8.9        69.6  Partially cloudy  
2        73.3   0.000        9.4        60.4  Partially cloudy  
3        78.7   0.036       10.1        60.2  rainpartlycloudy  
4        79.1   0.004        8.3        86.3  rainpartlycloudy  
..        ...     ...        ...         ...               ...  
969      86.0   0.028       13.6        90.4          Overcast  
970      84.7   0.032       14.1        65.1  Partially cloudy  
971      82.0   0.028       11.0        78.4  Partially cloudy  
972      79.9   0.024       10.5        94.4      rainovercast  
973      81.9   0.012       10.1        93.0          Overcast  

[974 rows x 12 columns]

In [12]:
testing

tempmax  tempmin  temp  feelslikemax  feelslikemin  feelslike   dew  \
0      81.2     68.8  73.4          84.3          68.8       73.8  67.7   
1      79.6     69.0  73.1          79.6          69.0       73.1  67.7   
2      77.4     69.9  72.4          77.4          69.9       72.4  67.9   
3      79.4     69.0  73.0          79.4          69.0       73.0  67.0   
4      80.5     67.7  73.0          83.2          67.7       73.2  67.0   
5      80.0     69.0  73.1          80.0          69.0       73.1  67.4   
6      78.5     68.8  72.5          78.5          68.8       72.5  67.0   
7      80.5     68.4  73.3          83.2          68.4       73.5  67.2   
8      81.4     68.3  73.8          84.0          68.3       74.3  67.0   
9      77.1     68.1  72.3          77.1          68.1       72.3  66.7   
10     80.9     67.4  73.3          83.1          67.4       73.6  66.2   
11     81.4     67.7  73.3          84.1          67.7       73.7  66.8   
12     77.8     67.6  72.1          77.8          67.6       72.1  66.8   
13     81.1     67.2  73.2          83.9          67.2       73.6  67.3   
14     81.6     68.3  73.9          84.9          68.3       74.4  68.0   

    humidity  precip  windspeed  cloudcover        conditions  
0       83.0   0.020       14.5        77.8  rainpartlycloudy  
1       83.8   0.024       15.7        71.2  Partially cloudy  
2       86.0   0.024       13.0        84.3  rainpartlycloudy  
3       82.2   0.008       14.8        59.7  rainpartlycloudy  
4       82.5   0.016       14.5        40.9  rainpartlycloudy  
5       83.1   0.028       14.1        42.0  Partially cloudy  
6       83.5   0.036       13.4        38.5  Partially cloudy  
7       82.0   0.036       12.8        50.3  Partially cloudy  
8       80.3   0.024       13.4        65.8  Partially cloudy  
9       83.1   0.012       11.2        92.5          Overcast  
10      79.6   0.020       11.9        24.4  Partially cloudy  
11      81.2   0.024       13.4        47.2  Partially cloudy  
12      83.8   0.004       10.5        89.9  Partially cloudy  
13      82.9   0.016       13.2        72.2  Partially cloudy  
14      83.1   0.047       13.2        66.7  Partially cloudy

In [13]:
X=training.loc[:,training.columns!="temp"].values
X_test=testing.loc[:,testing.columns!="temp"].values
y=training.loc[:,training.columns=="temp"].values
y_test=testing.loc[:,testing.columns=="temp"].values



In [14]:
X.shape

(974, 11)

In [15]:
X_test.shape

(15, 11)

In [16]:
y

array([[71.2],
       [71.6],
       [70.5],
       [70.7],
       [71.1],
       [72.9],
       [71.8],
       [71.5],
       [73.7],
       [74.4],
       [74. ],
       [72.9],
       [72.7],
       [72. ],
       [71.6],
       [72.6],
       [74.7],
       [75.3],
       [73.6],
       [73. ],
       [70.4],
       [70.7],
       [71.8],
       [71.2],
       [69.6],
       [69.8],
       [69.2],
       [69.4],
       [68.8],
       [69.8],
       [70.3],
       [70.1],
       [69.5],
       [68.3],
       [68.8],
       [69.5],
       [67.9],
       [67.7],
       [67.6],
       [68. ],
       [69.5],
       [71.9],
       [73. ],
       [72.4],
       [72.3],
       [72.1],
       [72. ],
       [72.7],
       [72.3],
       [70.3],
       [70.7],
       [72.9],
       [75. ],
       [76.5],
       [76.3],
       [76.6],
       [77.3],
       [76.9],
       [78.3],
       [79.4],
       [79. ],
       [78.1],
       [78.2],
       [78. ],
       [78.1],
       [78.8],
       [78

In [17]:
y_test

array([[73.4],
       [73.1],
       [72.4],
       [73. ],
       [73. ],
       [73.1],
       [72.5],
       [73.3],
       [73.8],
       [72.3],
       [73.3],
       [73.3],
       [72.1],
       [73.2],
       [73.9]])

In [18]:
condition_set=set(X[:,-1])

In [19]:
condition_set

{'Clear',
 'Overcast',
 'Partially cloudy',
 'Rain',
 'rainovercast',
 'rainpartlycloudy'}

In [20]:
condition_set_test=set(X_test[:,-1])
condition_set_test

{'Overcast', 'Partially cloudy', 'rainpartlycloudy'}

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X)).astype(np.float32)
X_test=np.array(ct.transform(X_test)).astype(np.float32)

In [22]:
X[0].shape

(16,)

In [23]:
X[0]

array([ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , 85.3, 60.9, 86.7, 60.9, 71.6,
       63.1, 77.3,  0. , 11. , 70.3], dtype=float32)

In [24]:
X_test[0]

array([0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00,
       8.12e+01, 6.88e+01, 8.43e+01, 6.88e+01, 7.38e+01, 6.77e+01,
       8.30e+01, 2.00e-02, 1.45e+01, 7.78e+01], dtype=float32)

In [25]:
X_test[0].shape

(16,)

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,6:]=sc.fit_transform(X[:,6:])
X_test[:,6:]=sc.transform(X_test[:,6:])


In [27]:
X[0]

array([ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        , -0.4114093 , -0.7940146 , -0.31946436, -0.7940146 ,
       -0.8589593 ,  0.24292757,  0.5926023 , -0.31653488, -0.1518722 ,
        0.5497843 ], dtype=float32)

In [28]:
X_test[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        , -0.985859  ,  0.39780554, -0.6850655 ,  0.39780554,
       -0.4405598 ,  0.7049613 ,  0.8793956 , -0.25363734,  0.69924134,
        0.78785026], dtype=float32)

In [29]:
import keras

model=keras.Sequential()
model.add(keras.layers.Dense(8,activation=keras.activations.relu))
model.add(keras.layers.Dense(8,activation=keras.activations.relu))
model.add(keras.layers.Dense(1))


In [30]:
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [31]:
model.fit(X,y,batch_size=32,epochs=200)

Epoch 1/200
31/31 [==============================] - 1s 1ms/step - loss: 5925.4478
Epoch 2/200
31/31 [==============================] - 0s 1ms/step - loss: 5870.4790
Epoch 3/200
31/31 [==============================] - 0s 915us/step - loss: 5827.7300
Epoch 4/200
31/31 [==============================] - 0s 736us/step - loss: 5784.7559
Epoch 5/200
31/31 [==============================] - 0s 713us/step - loss: 5732.2578
Epoch 6/200
31/31 [==============================] - 0s 722us/step - loss: 5660.0654
Epoch 7/200
31/31 [==============================] - 0s 673us/step - loss: 5552.1094
Epoch 8/200
31/31 [==============================] - 0s 729us/step - loss: 5398.4175
Epoch 9/200
31/31 [==============================] - 0s 752us/step - loss: 5189.7305
Epoch 10/200
31/31 [==============================] - 0s 1ms/step - loss: 4915.9790
Epoch 11/200
31/31 [==============================] - 0s 850us/step - loss: 4575.3618
Epoch 12/200
31/31 [==============================] - 0s 752us/step -

In [32]:
from sklearn.metrics import mean_absolute_error
y_pred=model.predict(X)
mean_absolute_error(y,y_pred)

31/31 [==============================] - 0s 527us/step


0.5090575286739906

In [33]:
for true,pred in zip(y,y_pred):
    print(true," -> ",pred," error= ",abs(true-pred))

[71.2]  ->  [71.62941]  error=  [0.42940979]
[71.6]  ->  [72.31341]  error=  [0.7134079]
[70.5]  ->  [70.761314]  error=  [0.26131439]
[70.7]  ->  [70.71743]  error=  [0.01743011]
[71.1]  ->  [72.31244]  error=  [1.21243896]
[72.9]  ->  [73.58148]  error=  [0.68148193]
[71.8]  ->  [71.35097]  error=  [0.44903259]
[71.5]  ->  [68.03359]  error=  [3.46640778]
[73.7]  ->  [72.72526]  error=  [0.97474213]
[74.4]  ->  [74.159805]  error=  [0.2401947]
[74.]  ->  [73.95665]  error=  [0.04335022]
[72.9]  ->  [73.50687]  error=  [0.60686646]
[72.7]  ->  [73.05873]  error=  [0.35873108]
[72.]  ->  [72.167305]  error=  [0.16730499]
[71.6]  ->  [72.04028]  error=  [0.4402832]
[72.6]  ->  [72.814735]  error=  [0.21473541]
[74.7]  ->  [75.09527]  error=  [0.39526825]
[75.3]  ->  [75.899994]  error=  [0.5999939]
[73.6]  ->  [73.49892]  error=  [0.10108337]
[73.]  ->  [73.57144]  error=  [0.57144165]
[70.4]  ->  [70.742714]  error=  [0.34271393]
[70.7]  ->  [70.37831]  error=  [0.32168884]
[71.8]  -> 

In [34]:
X.shape

(974, 16)

In [35]:
y_test

array([[73.4],
       [73.1],
       [72.4],
       [73. ],
       [73. ],
       [73.1],
       [72.5],
       [73.3],
       [73.8],
       [72.3],
       [73.3],
       [73.3],
       [72.1],
       [73.2],
       [73.9]])

In [36]:
X_test.shape

(15, 16)

In [37]:
y_pred_test=model.predict(X_test)
mean_absolute_error(y_test,y_pred_test)

1/1 [==============================] - 0s 16ms/step


0.4195298258463519

In [38]:
for true,pred in zip(y_test,y_pred_test):
    print(true," -> ",pred," error= ",abs(true-pred))

[73.4]  ->  [73.64959]  error=  [0.24958954]
[73.1]  ->  [73.08082]  error=  [0.01918182]
[72.4]  ->  [72.889206]  error=  [0.48920593]
[73.]  ->  [73.29452]  error=  [0.29451752]
[73.]  ->  [72.49974]  error=  [0.5002594]
[73.1]  ->  [72.770164]  error=  [0.32983551]
[72.5]  ->  [71.97676]  error=  [0.52323914]
[73.3]  ->  [72.721275]  error=  [0.57872467]
[73.8]  ->  [73.62061]  error=  [0.1793869]
[72.3]  ->  [71.53926]  error=  [0.76073914]
[73.3]  ->  [72.539604]  error=  [0.76039581]
[73.3]  ->  [72.83715]  error=  [0.46284943]
[72.1]  ->  [72.03825]  error=  [0.06174622]
[73.2]  ->  [72.77146]  error=  [0.42853851]
[73.9]  ->  [73.24526]  error=  [0.65473785]


In [40]:
model.save("modelv1.keras")

In [41]:
X_test[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        , -0.985859  ,  0.39780554, -0.6850655 ,  0.39780554,
       -0.4405598 ,  0.7049613 ,  0.8793956 , -0.25363734,  0.69924134,
        0.78785026], dtype=float32)

In [42]:
y_test[0]

array([73.4])