In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import sklearn
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv("storage_dataset/prototype_final_dataset.csv")
dataset

Date   Time  SM_2  SM_4  SM_8  SM_20  SM_40  ST_2  ST_4  ST_8  \
0     01-01-2022  00:00  38.2  35.9  31.0   36.9   34.0  15.9  15.5  15.5   
1     01-01-2022  01:00  38.2  36.0  30.9   36.7   34.1  16.0  15.6  15.6   
2     01-01-2022  02:00  38.3  36.0  31.0   36.7   33.9  16.0  15.6  15.6   
3     01-01-2022  03:00  38.3  35.8  30.9   36.7   33.9  16.1  15.7  15.6   
4     01-01-2022  04:00  38.3  35.9  30.9   36.7   33.9  16.2  15.7  15.7   
...          ...    ...   ...   ...   ...    ...    ...   ...   ...   ...   
8755  31-12-2022  19:00  36.8  36.5  30.6   34.7   31.8  10.5  10.1  10.0   
8756  31-12-2022  20:00  36.7  36.2  30.5   34.7   31.8  10.2  10.0   9.9   
8757  31-12-2022  21:00  36.5  36.1  30.3   34.9   31.8   9.9   9.9   9.8   
8758  31-12-2022  22:00  36.5  36.1  30.3   34.8   32.0   9.7   9.7   9.8   
8759  31-12-2022  23:00  37.2  36.0  30.3   34.8   32.0   9.4   9.6   9.7   

      ...  sealevelpressure  cloudcover  visibility  solarradiation  \
0     ...            1009.4       100.0        16.0             0.0   
1     ...            1009.3        91.7        16.0             0.0   
2     ...            1009.3        62.7        16.0             0.0   
3     ...            1009.3        91.7        16.0             0.0   
4     ...            1009.6       100.0        16.0             0.0   
...   ...               ...         ...         ...             ...   
8755  ...               NaN         NaN         NaN             NaN   
8756  ...               NaN         NaN         NaN             NaN   
8757  ...               NaN         NaN         NaN             NaN   
8758  ...               NaN         NaN         NaN             NaN   
8759  ...               NaN         NaN         NaN             NaN   

      solarenergy  uvindex  severerisk        conditions                 icon  \
0             0.0      0.0         NaN          Overcast               cloudy   
1             0.0      0.0         NaN          Overcast               cloudy   
2             0.0      0.0         NaN  Partially cloudy  partly-cloudy-night   
3             0.0      0.0         NaN          Overcast               cloudy   
4             0.0      0.0         NaN          Overcast               cloudy   
...           ...      ...         ...               ...                  ...   
8755          NaN      NaN         NaN               NaN                  NaN   
8756          NaN      NaN         NaN               NaN                  NaN   
8757          NaN      NaN         NaN               NaN                  NaN   
8758          NaN      NaN         NaN               NaN                  NaN   
8759          NaN      NaN         NaN               NaN                  NaN   

                                     stations  
0     KHSV,72323003856,72030763804,KMDQ,AAMA1  
1     KHSV,72323003856,72030763804,KMDQ,AAMA1  
2     KHSV,72323003856,72030763804,KMDQ,AAMA1  
3     KHSV,72323003856,72030763804,KMDQ,AAMA1  
4           KHSV,72323003856,72030763804,KMDQ  
...                                       ...  
8755                                      NaN  
8756                                      NaN  
8757                                      NaN  
8758                                      NaN  
8759                                      NaN  

[8760 rows x 34 columns]

In [3]:
dataset.columns

Index(['Date', 'Time', 'SM_2', 'SM_4', 'SM_8', 'SM_20', 'SM_40', 'ST_2',
       'ST_4', 'ST_8', 'ST_20', 'ST_40', 'temp', 'feelslike', 'dew',
       'humidity', 'precip', 'precipprob', 'preciptype', 'snow', 'snowdepth',
       'windgust', 'windspeed', 'winddir', 'sealevelpressure', 'cloudcover',
       'visibility', 'solarradiation', 'solarenergy', 'uvindex', 'severerisk',
       'conditions', 'icon', 'stations'],
      dtype='object')

In [4]:
dataset.__len__()

8760

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Date              8760 non-null   object 
 1   Time              8760 non-null   object 
 2   SM_2              8760 non-null   float64
 3   SM_4              8760 non-null   float64
 4   SM_8              8760 non-null   float64
 5   SM_20             8760 non-null   float64
 6   SM_40             8760 non-null   float64
 7   ST_2              8760 non-null   float64
 8   ST_4              8760 non-null   float64
 9   ST_8              8760 non-null   float64
 10  ST_20             8760 non-null   float64
 11  ST_40             8760 non-null   float64
 12  temp              2879 non-null   float64
 13  feelslike         2879 non-null   float64
 14  dew               2879 non-null   float64
 15  humidity          2879 non-null   float64
 16  precip            2879 non-null   float64


In [6]:
dataset.__len__()

8760

In [7]:
dataset

Date   Time  SM_2  SM_4  SM_8  SM_20  SM_40  ST_2  ST_4  ST_8  \
0     01-01-2022  00:00  38.2  35.9  31.0   36.9   34.0  15.9  15.5  15.5   
1     01-01-2022  01:00  38.2  36.0  30.9   36.7   34.1  16.0  15.6  15.6   
2     01-01-2022  02:00  38.3  36.0  31.0   36.7   33.9  16.0  15.6  15.6   
3     01-01-2022  03:00  38.3  35.8  30.9   36.7   33.9  16.1  15.7  15.6   
4     01-01-2022  04:00  38.3  35.9  30.9   36.7   33.9  16.2  15.7  15.7   
...          ...    ...   ...   ...   ...    ...    ...   ...   ...   ...   
8755  31-12-2022  19:00  36.8  36.5  30.6   34.7   31.8  10.5  10.1  10.0   
8756  31-12-2022  20:00  36.7  36.2  30.5   34.7   31.8  10.2  10.0   9.9   
8757  31-12-2022  21:00  36.5  36.1  30.3   34.9   31.8   9.9   9.9   9.8   
8758  31-12-2022  22:00  36.5  36.1  30.3   34.8   32.0   9.7   9.7   9.8   
8759  31-12-2022  23:00  37.2  36.0  30.3   34.8   32.0   9.4   9.6   9.7   

      ...  sealevelpressure  cloudcover  visibility  solarradiation  \
0     ...            1009.4       100.0        16.0             0.0   
1     ...            1009.3        91.7        16.0             0.0   
2     ...            1009.3        62.7        16.0             0.0   
3     ...            1009.3        91.7        16.0             0.0   
4     ...            1009.6       100.0        16.0             0.0   
...   ...               ...         ...         ...             ...   
8755  ...               NaN         NaN         NaN             NaN   
8756  ...               NaN         NaN         NaN             NaN   
8757  ...               NaN         NaN         NaN             NaN   
8758  ...               NaN         NaN         NaN             NaN   
8759  ...               NaN         NaN         NaN             NaN   

      solarenergy  uvindex  severerisk        conditions                 icon  \
0             0.0      0.0         NaN          Overcast               cloudy   
1             0.0      0.0         NaN          Overcast               cloudy   
2             0.0      0.0         NaN  Partially cloudy  partly-cloudy-night   
3             0.0      0.0         NaN          Overcast               cloudy   
4             0.0      0.0         NaN          Overcast               cloudy   
...           ...      ...         ...               ...                  ...   
8755          NaN      NaN         NaN               NaN                  NaN   
8756          NaN      NaN         NaN               NaN                  NaN   
8757          NaN      NaN         NaN               NaN                  NaN   
8758          NaN      NaN         NaN               NaN                  NaN   
8759          NaN      NaN         NaN               NaN                  NaN   

                                     stations  
0     KHSV,72323003856,72030763804,KMDQ,AAMA1  
1     KHSV,72323003856,72030763804,KMDQ,AAMA1  
2     KHSV,72323003856,72030763804,KMDQ,AAMA1  
3     KHSV,72323003856,72030763804,KMDQ,AAMA1  
4           KHSV,72323003856,72030763804,KMDQ  
...                                       ...  
8755                                      NaN  
8756                                      NaN  
8757                                      NaN  
8758                                      NaN  
8759                                      NaN  

[8760 rows x 34 columns]

In [8]:
dataset.drop(
    [
        "Date",
        "SM_2",
        "SM_8",
        "SM_20",
        "SM_40",
        "ST_2",
        "ST_8",
        "ST_20",
        "ST_40",
        "solarenergy",
        "precipprob",
        "preciptype",
        "snow",
        "snowdepth",
        "windgust",
        "winddir",
        "sealevelpressure",
        "visibility",
        "solarenergy",
        "uvindex",
        "severerisk",
        "icon",
        "stations",
        "dew",
        "solarradiation",
        "Time",
        # "cloudcover",
        "feelslike",
        # "windspeed",
    ],
    inplace=True,
    axis=1,
)

In [9]:
dataset

Time  SM_4  ST_4  temp  humidity  precip  windspeed  cloudcover  \
0     00:00  35.9  15.5  21.6     84.50     0.0       22.3       100.0   
1     01:00  36.0  15.6  21.6     84.97     0.0       27.7        91.7   
2     02:00  36.0  15.6  21.2     86.87     0.0       22.8        62.7   
3     03:00  35.8  15.7  21.2     86.66     0.0       22.8        91.7   
4     04:00  35.9  15.7  21.6     84.50     0.0       19.8       100.0   
...     ...   ...   ...   ...       ...     ...        ...         ...   
8755  19:00  36.5  10.1   NaN       NaN     NaN        NaN         NaN   
8756  20:00  36.2  10.0   NaN       NaN     NaN        NaN         NaN   
8757  21:00  36.1   9.9   NaN       NaN     NaN        NaN         NaN   
8758  22:00  36.1   9.7   NaN       NaN     NaN        NaN         NaN   
8759  23:00  36.0   9.6   NaN       NaN     NaN        NaN         NaN   

            conditions  
0             Overcast  
1             Overcast  
2     Partially cloudy  
3             Overcast  
4             Overcast  
...                ...  
8755               NaN  
8756               NaN  
8757               NaN  
8758               NaN  
8759               NaN  

[8760 rows x 9 columns]

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Time        8760 non-null   object 
 1   SM_4        8760 non-null   float64
 2   ST_4        8760 non-null   float64
 3   temp        2879 non-null   float64
 4   humidity    2879 non-null   float64
 5   precip      2879 non-null   float64
 6   windspeed   2879 non-null   float64
 7   cloudcover  2879 non-null   float64
 8   conditions  2879 non-null   object 
dtypes: float64(7), object(2)
memory usage: 616.1+ KB


In [11]:
dataset = dataset.dropna()

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2879 entries, 0 to 2879
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Time        2879 non-null   object 
 1   SM_4        2879 non-null   float64
 2   ST_4        2879 non-null   float64
 3   temp        2879 non-null   float64
 4   humidity    2879 non-null   float64
 5   precip      2879 non-null   float64
 6   windspeed   2879 non-null   float64
 7   cloudcover  2879 non-null   float64
 8   conditions  2879 non-null   object 
dtypes: float64(7), object(2)
memory usage: 224.9+ KB


In [13]:
dataset

Time  SM_4  ST_4  temp  humidity  precip  windspeed  cloudcover  \
0     00:00  35.9  15.5  21.6     84.50     0.0       22.3       100.0   
1     01:00  36.0  15.6  21.6     84.97     0.0       27.7        91.7   
2     02:00  36.0  15.6  21.2     86.87     0.0       22.8        62.7   
3     03:00  35.8  15.7  21.2     86.66     0.0       22.8        91.7   
4     04:00  35.9  15.7  21.6     84.50     0.0       19.8       100.0   
...     ...   ...   ...   ...       ...     ...        ...         ...   
2875  19:00  23.4  18.9  24.7     64.43     0.0       10.6        87.7   
2876  20:00  23.5  18.8  22.6     73.48     0.0        3.4        35.5   
2877  21:00  23.4  18.7  22.0     77.15     0.0       18.6        49.4   
2878  22:00  23.4  18.6  20.3     82.27     0.0       16.5        24.8   
2879  23:00  23.4  18.5  19.7     85.41     0.0       15.3         7.8   

            conditions  
0             Overcast  
1             Overcast  
2     Partially cloudy  
3             Overcast  
4             Overcast  
...                ...  
2875  Partially cloudy  
2876  Partially cloudy  
2877  Partially cloudy  
2878  Partially cloudy  
2879             Clear  

[2879 rows x 9 columns]

In [14]:
X = dataset.iloc[:, 1:].values
X

array([[35.9, 15.5, 21.6, ..., 22.3, 100.0, 'Overcast'],
       [36.0, 15.6, 21.6, ..., 27.7, 91.7, 'Overcast'],
       [36.0, 15.6, 21.2, ..., 22.8, 62.7, 'Partially cloudy'],
       ...,
       [23.4, 18.7, 22.0, ..., 18.6, 49.4, 'Partially cloudy'],
       [23.4, 18.6, 20.3, ..., 16.5, 24.8, 'Partially cloudy'],
       [23.4, 18.5, 19.7, ..., 15.3, 7.8, 'Clear']], dtype=object)

In [15]:
y = dataset.iloc[:, 0].values
y

array(['00:00', '01:00', '02:00', ..., '21:00', '22:00', '23:00'],
      dtype=object)

In [16]:
""" taking care of categorical data in conditions column """
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [-1])], remainder="passthrough"
)
X = np.array(ct.fit_transform(X))
X

array([[0.0, 1.0, 0.0, ..., 0.0, 22.3, 100.0],
       [0.0, 1.0, 0.0, ..., 0.0, 27.7, 91.7],
       [0.0, 0.0, 1.0, ..., 0.0, 22.8, 62.7],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 18.6, 49.4],
       [0.0, 0.0, 1.0, ..., 0.0, 16.5, 24.8],
       [1.0, 0.0, 0.0, ..., 0.0, 15.3, 7.8]], dtype=object)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

In [18]:
X_train.shape

(2159, 15)

In [19]:
y_train.shape

(2159,)

In [20]:
X_test.shape

(720, 15)

In [21]:
y_test.shape

(720,)

In [22]:
X_train[0]

array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 30.7, 15.0, 21.5, 71.37,
       0.0, 28.2, 89.0], dtype=object)

In [23]:
y_train[0]

'10:00'

In [24]:
""" Scaling data """
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
X_train[:, 8:] = sc.fit_transform(X_train[:, 8:])
X_test[:, 8:] = sc.transform(X_test[:, 8:])
X_train[0]

array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3187772925764194,
       0.7345679012345678, 0.8152173913043479, 0.6670543086405397, 0.0,
       0.5924369747899159, 0.89], dtype=object)

In [25]:
X_train[0]

array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3187772925764194,
       0.7345679012345678, 0.8152173913043479, 0.6670543086405397, 0.0,
       0.5924369747899159, 0.89], dtype=object)

In [26]:
X_test[0]

array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.751091703056769,
       0.32716049382716056, 0.5516304347826088, 0.942202581695546,
       0.007200000000000001, 0.3697478991596639, 1.0], dtype=object)

In [27]:
X_train[0].shape

(15,)

<h1>ANN model </h1>

In [28]:
""" Model """
model = keras.Sequential(
    [
        keras.layers.Dense(15, activation=keras.activations.relu),
        keras.layers.Dense(12, activation=keras.activations.relu),
        keras.layers.Dense(8, activation=keras.activations.relu),
        keras.layers.Dense(4, activation=keras.activations.relu),
        keras.layers.Dense(2, activation=keras.activations.relu),
        keras.layers.Dense(1),
    ]
)

In [29]:
model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.mean_squared_error,
    metrics=keras.metrics.mean_absolute_error,
)

In [30]:
X_train = np.asarray(X_train).astype("float32")
y_train = np.asarray(y_train).astype("float32")

ValueError: could not convert string to float: '10:00'

In [ ]:
X_train[0]

In [ ]:
history = model.fit(X_train, y_train, epochs=5)
model.summary()

In [ ]:
plt.plot(history.history["loss"])
plt.title("Training Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

In [ ]:
X_test = np.asarray(X_test).astype("float32")
y_test = np.asarray(y_test).astype("float32")

In [ ]:
y_pred = model.predict(X_test).reshape(-1, 1)
y_pred

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

annMAR = mean_absolute_error(y_test, y_pred)
annMSR = mean_squared_error(y_test, y_pred)
print(annMAR)
print(annMSR)

In [ ]:
to_predit = X_train[0].reshape(-1, X_train.shape[1])

In [ ]:
model.predict(to_predit)

In [ ]:
y_train[0]

In [ ]:
for idx in range(20):
    to_predit = X_test[idx].reshape(-1, X_test.shape[1])
    print(y_test[idx], " --> ", model.predict(to_predit))

In [ ]:
# prototype = model.save(filepath="zeus.h5")

<h1> MLR model </h1>

In [ ]:
from sklearn.linear_model import LinearRegression

mlrModel = LinearRegression()
mlrModel.fit(X_train, y_train)

In [ ]:
mlr_ypred = mlrModel.predict(X_test)

In [ ]:
mlr_MAR = mean_absolute_error(y_test, mlr_ypred)
mlr_MSR = mean_squared_error(y_test, mlr_ypred)
print(mlr_MAR)
print(mlr_MSR)

In [ ]:
for idx in range(20):
    to_predit = X_test[idx].reshape(-1, X_test.shape[1])
    print(y_test[idx], " --> ", model.predict(to_predit))