In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import sklearn as sk

In [2]:
dataset = pd.read_csv("./storage_dataset/prototype_final_dataset.csv")
dataset

Date   Time  SM_2  SM_4  SM_8  SM_20  SM_40  ST_2  ST_4  ST_8  \
0     01-01-2022  00:00  38.2  35.9  31.0   36.9   34.0  15.9  15.5  15.5   
1     01-01-2022  01:00  38.2  36.0  30.9   36.7   34.1  16.0  15.6  15.6   
2     01-01-2022  02:00  38.3  36.0  31.0   36.7   33.9  16.0  15.6  15.6   
3     01-01-2022  03:00  38.3  35.8  30.9   36.7   33.9  16.1  15.7  15.6   
4     01-01-2022  04:00  38.3  35.9  30.9   36.7   33.9  16.2  15.7  15.7   
...          ...    ...   ...   ...   ...    ...    ...   ...   ...   ...   
8755  31-12-2022  19:00  36.8  36.5  30.6   34.7   31.8  10.5  10.1  10.0   
8756  31-12-2022  20:00  36.7  36.2  30.5   34.7   31.8  10.2  10.0   9.9   
8757  31-12-2022  21:00  36.5  36.1  30.3   34.9   31.8   9.9   9.9   9.8   
8758  31-12-2022  22:00  36.5  36.1  30.3   34.8   32.0   9.7   9.7   9.8   
8759  31-12-2022  23:00  37.2  36.0  30.3   34.8   32.0   9.4   9.6   9.7   

      ...  sealevelpressure  cloudcover  visibility  solarradiation  \
0     ...            1009.4       100.0        16.0             0.0   
1     ...            1009.3        91.7        16.0             0.0   
2     ...            1009.3        62.7        16.0             0.0   
3     ...            1009.3        91.7        16.0             0.0   
4     ...            1009.6       100.0        16.0             0.0   
...   ...               ...         ...         ...             ...   
8755  ...               NaN         NaN         NaN             NaN   
8756  ...               NaN         NaN         NaN             NaN   
8757  ...               NaN         NaN         NaN             NaN   
8758  ...               NaN         NaN         NaN             NaN   
8759  ...               NaN         NaN         NaN             NaN   

      solarenergy  uvindex  severerisk        conditions                 icon  \
0             0.0      0.0         NaN          Overcast               cloudy   
1             0.0      0.0         NaN          Overcast               cloudy   
2             0.0      0.0         NaN  Partially cloudy  partly-cloudy-night   
3             0.0      0.0         NaN          Overcast               cloudy   
4             0.0      0.0         NaN          Overcast               cloudy   
...           ...      ...         ...               ...                  ...   
8755          NaN      NaN         NaN               NaN                  NaN   
8756          NaN      NaN         NaN               NaN                  NaN   
8757          NaN      NaN         NaN               NaN                  NaN   
8758          NaN      NaN         NaN               NaN                  NaN   
8759          NaN      NaN         NaN               NaN                  NaN   

                                     stations  
0     KHSV,72323003856,72030763804,KMDQ,AAMA1  
1     KHSV,72323003856,72030763804,KMDQ,AAMA1  
2     KHSV,72323003856,72030763804,KMDQ,AAMA1  
3     KHSV,72323003856,72030763804,KMDQ,AAMA1  
4           KHSV,72323003856,72030763804,KMDQ  
...                                       ...  
8755                                      NaN  
8756                                      NaN  
8757                                      NaN  
8758                                      NaN  
8759                                      NaN  

[8760 rows x 34 columns]

In [3]:
dataset.columns

Index(['Date', 'Time', 'SM_2', 'SM_4', 'SM_8', 'SM_20', 'SM_40', 'ST_2',
       'ST_4', 'ST_8', 'ST_20', 'ST_40', 'temp', 'feelslike', 'dew',
       'humidity', 'precip', 'precipprob', 'preciptype', 'snow', 'snowdepth',
       'windgust', 'windspeed', 'winddir', 'sealevelpressure', 'cloudcover',
       'visibility', 'solarradiation', 'solarenergy', 'uvindex', 'severerisk',
       'conditions', 'icon', 'stations'],
      dtype='object')

In [4]:
dataset.__len__()

8760

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Date              8760 non-null   object 
 1   Time              8760 non-null   object 
 2   SM_2              8760 non-null   float64
 3   SM_4              8760 non-null   float64
 4   SM_8              8760 non-null   float64
 5   SM_20             8760 non-null   float64
 6   SM_40             8760 non-null   float64
 7   ST_2              8760 non-null   float64
 8   ST_4              8760 non-null   float64
 9   ST_8              8760 non-null   float64
 10  ST_20             8760 non-null   float64
 11  ST_40             8760 non-null   float64
 12  temp              2879 non-null   float64
 13  feelslike         2879 non-null   float64
 14  dew               2879 non-null   float64
 15  humidity          2879 non-null   float64
 16  precip            2879 non-null   float64


In [6]:
dataset.__len__()

8760

In [7]:
dataset

Date   Time  SM_2  SM_4  SM_8  SM_20  SM_40  ST_2  ST_4  ST_8  \
0     01-01-2022  00:00  38.2  35.9  31.0   36.9   34.0  15.9  15.5  15.5   
1     01-01-2022  01:00  38.2  36.0  30.9   36.7   34.1  16.0  15.6  15.6   
2     01-01-2022  02:00  38.3  36.0  31.0   36.7   33.9  16.0  15.6  15.6   
3     01-01-2022  03:00  38.3  35.8  30.9   36.7   33.9  16.1  15.7  15.6   
4     01-01-2022  04:00  38.3  35.9  30.9   36.7   33.9  16.2  15.7  15.7   
...          ...    ...   ...   ...   ...    ...    ...   ...   ...   ...   
8755  31-12-2022  19:00  36.8  36.5  30.6   34.7   31.8  10.5  10.1  10.0   
8756  31-12-2022  20:00  36.7  36.2  30.5   34.7   31.8  10.2  10.0   9.9   
8757  31-12-2022  21:00  36.5  36.1  30.3   34.9   31.8   9.9   9.9   9.8   
8758  31-12-2022  22:00  36.5  36.1  30.3   34.8   32.0   9.7   9.7   9.8   
8759  31-12-2022  23:00  37.2  36.0  30.3   34.8   32.0   9.4   9.6   9.7   

      ...  sealevelpressure  cloudcover  visibility  solarradiation  \
0     ...            1009.4       100.0        16.0             0.0   
1     ...            1009.3        91.7        16.0             0.0   
2     ...            1009.3        62.7        16.0             0.0   
3     ...            1009.3        91.7        16.0             0.0   
4     ...            1009.6       100.0        16.0             0.0   
...   ...               ...         ...         ...             ...   
8755  ...               NaN         NaN         NaN             NaN   
8756  ...               NaN         NaN         NaN             NaN   
8757  ...               NaN         NaN         NaN             NaN   
8758  ...               NaN         NaN         NaN             NaN   
8759  ...               NaN         NaN         NaN             NaN   

      solarenergy  uvindex  severerisk        conditions                 icon  \
0             0.0      0.0         NaN          Overcast               cloudy   
1             0.0      0.0         NaN          Overcast               cloudy   
2             0.0      0.0         NaN  Partially cloudy  partly-cloudy-night   
3             0.0      0.0         NaN          Overcast               cloudy   
4             0.0      0.0         NaN          Overcast               cloudy   
...           ...      ...         ...               ...                  ...   
8755          NaN      NaN         NaN               NaN                  NaN   
8756          NaN      NaN         NaN               NaN                  NaN   
8757          NaN      NaN         NaN               NaN                  NaN   
8758          NaN      NaN         NaN               NaN                  NaN   
8759          NaN      NaN         NaN               NaN                  NaN   

                                     stations  
0     KHSV,72323003856,72030763804,KMDQ,AAMA1  
1     KHSV,72323003856,72030763804,KMDQ,AAMA1  
2     KHSV,72323003856,72030763804,KMDQ,AAMA1  
3     KHSV,72323003856,72030763804,KMDQ,AAMA1  
4           KHSV,72323003856,72030763804,KMDQ  
...                                       ...  
8755                                      NaN  
8756                                      NaN  
8757                                      NaN  
8758                                      NaN  
8759                                      NaN  

[8760 rows x 34 columns]

In [8]:
dataset.drop(
    [
        "Date",
        "SM_4",
        "SM_8",
        "SM_20",
        "SM_40",
        "ST_4",
        "ST_8",
        "ST_20",
        "ST_40",
        "feelslike",
        "solarenergy",
        "precipprob",
        "preciptype",
        "snow",
        "snowdepth",
        "windgust",
        "winddir",
        "sealevelpressure",
        "visibility",
        "solarenergy",
        "uvindex",
        "severerisk",
        "icon",
        "stations",
        "dew",
        "conditions",
        "solarradiation",
        "Time"
    ],
    inplace=True,
    axis=1,
)

In [9]:
dataset

SM_2  ST_2  temp  humidity  precip  windspeed  cloudcover
0     38.2  15.9  21.6     84.50     0.0       22.3       100.0
1     38.2  16.0  21.6     84.97     0.0       27.7        91.7
2     38.3  16.0  21.2     86.87     0.0       22.8        62.7
3     38.3  16.1  21.2     86.66     0.0       22.8        91.7
4     38.3  16.2  21.6     84.50     0.0       19.8       100.0
...    ...   ...   ...       ...     ...        ...         ...
8755  36.8  10.5   NaN       NaN     NaN        NaN         NaN
8756  36.7  10.2   NaN       NaN     NaN        NaN         NaN
8757  36.5   9.9   NaN       NaN     NaN        NaN         NaN
8758  36.5   9.7   NaN       NaN     NaN        NaN         NaN
8759  37.2   9.4   NaN       NaN     NaN        NaN         NaN

[8760 rows x 7 columns]

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   SM_2        8760 non-null   float64
 1   ST_2        8760 non-null   float64
 2   temp        2879 non-null   float64
 3   humidity    2879 non-null   float64
 4   precip      2879 non-null   float64
 5   windspeed   2879 non-null   float64
 6   cloudcover  2879 non-null   float64
dtypes: float64(7)
memory usage: 479.2 KB


In [11]:
dataset=dataset.dropna()

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2879 entries, 0 to 2879
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   SM_2        2879 non-null   float64
 1   ST_2        2879 non-null   float64
 2   temp        2879 non-null   float64
 3   humidity    2879 non-null   float64
 4   precip      2879 non-null   float64
 5   windspeed   2879 non-null   float64
 6   cloudcover  2879 non-null   float64
dtypes: float64(7)
memory usage: 179.9 KB


In [13]:
dataset

SM_2  ST_2  temp  humidity  precip  windspeed  cloudcover
0     38.2  15.9  21.6     84.50     0.0       22.3       100.0
1     38.2  16.0  21.6     84.97     0.0       27.7        91.7
2     38.3  16.0  21.2     86.87     0.0       22.8        62.7
3     38.3  16.1  21.2     86.66     0.0       22.8        91.7
4     38.3  16.2  21.6     84.50     0.0       19.8       100.0
...    ...   ...   ...       ...     ...        ...         ...
2875  21.8  19.4  24.7     64.43     0.0       10.6        87.7
2876  21.8  19.1  22.6     73.48     0.0        3.4        35.5
2877  21.6  18.9  22.0     77.15     0.0       18.6        49.4
2878  21.7  18.7  20.3     82.27     0.0       16.5        24.8
2879  21.5  18.6  19.7     85.41     0.0       15.3         7.8

[2879 rows x 7 columns]

In [14]:
X_train=dataset.iloc[:,1:].values
X_train

array([[ 15.9 ,  21.6 ,  84.5 ,   0.  ,  22.3 , 100.  ],
       [ 16.  ,  21.6 ,  84.97,   0.  ,  27.7 ,  91.7 ],
       [ 16.  ,  21.2 ,  86.87,   0.  ,  22.8 ,  62.7 ],
       ...,
       [ 18.9 ,  22.  ,  77.15,   0.  ,  18.6 ,  49.4 ],
       [ 18.7 ,  20.3 ,  82.27,   0.  ,  16.5 ,  24.8 ],
       [ 18.6 ,  19.7 ,  85.41,   0.  ,  15.3 ,   7.8 ]])

In [15]:
y_train=dataset.iloc[:,0].values
y_train

array([38.2, 38.2, 38.3, ..., 21.6, 21.7, 21.5])

In [ ]:
# """ taking care of categorical data in conditions column """
# from sklearn.compose import  ColumnTransformer
# from sklearn.preprocessing import  OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [10])], remainder='passthrough')
# X_train = np.array(ct.fit_transform(X_train))
# X_train

In [16]:
X_train.shape

(2879, 6)

In [17]:
y_train.shape

(2879,)

In [18]:
X_train[0]

array([ 15.9,  21.6,  84.5,   0. ,  22.3, 100. ])

In [19]:
""" Standard Scaling data """
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,:]=sc.fit_transform(X_train[:,:])
X_train[0]

array([ 1.30183136,  1.47600499,  0.81931337, -0.15776834,  1.25279781,
        1.21711691])

In [20]:
X_train[0].shape

(6,)

In [21]:
""" Model """
model=keras.Sequential(
    [
        keras.layers.Dense(22,activation=keras.activations.relu),
        keras.layers.Dense(44,activation=keras.activations.relu),
        keras.layers.Dense(1)
    ]
)

In [22]:
model.compile(optimizer=keras.optimizers.Adam(),loss=keras.losses.mean_squared_error,metrics=keras.metrics.mean_absolute_error)

In [23]:
X_train=np.asarray(X_train).astype("float32")
y_train=np.asarray(y_train).astype("float32")

In [24]:
model.fit(X_train,y_train,epochs=50)

Epoch 1/50
90/90 [==============================] - 3s 1ms/step - loss: 1037.2084 - mean_absolute_error: 31.7811
Epoch 2/50
90/90 [==============================] - 0s 882us/step - loss: 457.0378 - mean_absolute_error: 19.7635
Epoch 3/50
90/90 [==============================] - 0s 912us/step - loss: 78.7270 - mean_absolute_error: 7.1309
Epoch 4/50
90/90 [==============================] - 0s 1ms/step - loss: 45.8696 - mean_absolute_error: 5.3196
Epoch 5/50
90/90 [==============================] - 0s 820us/step - loss: 38.5179 - mean_absolute_error: 4.8684
Epoch 6/50
90/90 [==============================] - 0s 884us/step - loss: 33.9976 - mean_absolute_error: 4.5617
Epoch 7/50
90/90 [==============================] - 0s 890us/step - loss: 30.7097 - mean_absolute_error: 4.3159
Epoch 8/50
90/90 [==============================] - 0s 1ms/step - loss: 28.1261 - mean_absolute_error: 4.1165
Epoch 9/50
90/90 [==============================] - 0s 857us/step - loss: 25.9909 - mean_absolute_error: 

In [25]:
y_pred=model.predict(X_train).reshape(-1,1)
y_pred

90/90 [==============================] - 0s 677us/step


array([[33.681   ],
       [33.17993 ],
       [30.987244],
       ...,
       [23.543867],
       [24.470486],
       [26.12412 ]], dtype=float32)

In [26]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_train,y_pred)

2.3772988

In [27]:
X_train.shape

(2879, 6)

In [28]:
model.input_shape

(None, 6)

In [30]:
to_predit=X_train[0].reshape(-1,6)

In [31]:
model.predict(to_predit)

1/1 [==============================] - 0s 13ms/step


array([[33.681]], dtype=float32)

In [32]:
y_train[0]

38.2

In [34]:
for idx in range(10):
    to_predit=X_train[idx].reshape(-1,6)
    print(y_train[idx]," --> ", model.predict(to_predit))

1/1 [==============================] - 0s 14ms/step
38.2  -->  [[33.681]]
1/1 [==============================] - 0s 14ms/step
38.2  -->  [[33.179928]]
1/1 [==============================] - 0s 15ms/step
38.3  -->  [[30.987244]]
1/1 [==============================] - 0s 17ms/step
38.3  -->  [[33.130505]]
1/1 [==============================] - 0s 14ms/step
38.3  -->  [[33.33496]]
1/1 [==============================] - 0s 16ms/step
38.3  -->  [[32.534584]]
1/1 [==============================] - 0s 15ms/step
38.3  -->  [[29.347017]]
1/1 [==============================] - 0s 15ms/step
38.3  -->  [[30.027548]]
1/1 [==============================] - 0s 16ms/step
38.2  -->  [[32.366966]]
1/1 [==============================] - 0s 15ms/step
38.3  -->  [[31.875406]]
