In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import sklearn as sk

In [2]:
dataset = pd.read_csv("soil_moisture_temperature_training_data_22_23.csv")
dataset

Site Id        Date  SM_2  SM_4  SM_8  SM_20  SM_40  ST_2  ST_4  ST_8  \
0       2078  01-01-2022  38.2  35.9  31.0   36.9   34.0  15.9  15.5  15.5   
1       2078  02-01-2022  41.7  40.5  34.4   39.9   36.6  15.7  16.0  16.4   
2       2078  03-01-2022  40.8  39.2  34.1   41.2   34.5  11.8  13.6  13.8   
3       2078  04-01-2022  40.4  38.4  33.3   39.2   35.5   9.3  11.0  11.0   
4       2078  05-01-2022  41.6  39.7  35.7   46.0   34.9   7.3   9.0   9.2   
..       ...         ...   ...   ...   ...    ...    ...   ...   ...   ...   
664     2078  27-10-2023  18.0  18.0  16.4   29.5   28.2  18.8  19.3  19.6   
665     2078  28-10-2023  18.2  18.0  16.5   29.6   28.3  19.2  19.9  20.1   
666     2078  29-10-2023  18.4  17.9  16.5   29.6   28.3  20.0  20.5  20.7   
667     2078  30-10-2023  18.0  18.0  16.3   29.5   28.2  19.0  20.0  20.5   
668     2078  31-10-2023  16.6  17.3  15.9   29.5   28.3  14.2  16.4  17.1   

     ...  solarenergy  uvindex  severerisk              sunrise  \
0    ...          5.8        4         NaN  2022-01-01T06:53:32   
1    ...          1.7        1         NaN  2022-01-02T06:53:43   
2    ...          0.9        0         NaN  2022-01-03T06:53:51   
3    ...          9.8        5         NaN  2022-01-04T06:53:57   
4    ...          4.4        3         NaN  2022-01-05T06:54:02   
..   ...          ...      ...         ...                  ...   
664  ...          8.0        4        10.0  2023-10-27T07:02:06   
665  ...          9.4        6        10.0  2023-10-28T07:03:00   
666  ...          9.1        6        10.0  2023-10-29T07:03:54   
667  ...          1.8        1        10.0  2023-10-30T07:04:49   
668  ...         13.4        7        10.0  2023-10-31T07:05:44   

                  sunset  moonphase              conditions  \
0    2022-01-01T16:46:47       0.96  Rain, Partially cloudy   
1    2022-01-02T16:47:33       0.00    Snow, Rain, Overcast   
2    2022-01-03T16:48:21       0.03    Snow, Rain, Overcast   
3    2022-01-04T16:49:09       0.06                   Clear   
4    2022-01-05T16:49:59       0.10        Partially cloudy   
..                   ...        ...                     ...   
664  2023-10-27T17:58:00       0.46        Partially cloudy   
665  2023-10-28T17:56:56       0.50        Partially cloudy   
666  2023-10-29T17:55:53       0.53        Partially cloudy   
667  2023-10-30T17:54:52       0.56          Rain, Overcast   
668  2023-10-31T17:53:52       0.59        Partially cloudy   

                                           description               icon  \
0          Partly cloudy throughout the day with rain.               rain   
1    Cloudy skies throughout the day with rain or s...               rain   
2    Cloudy skies throughout the day with rain or s...               snow   
3                 Clear conditions throughout the day.          clear-day   
4                    Partly cloudy throughout the day.  partly-cloudy-day   
..                                                 ...                ...   
664                  Partly cloudy throughout the day.  partly-cloudy-day   
665                  Partly cloudy throughout the day.  partly-cloudy-day   
666                  Becoming cloudy in the afternoon.  partly-cloudy-day   
667  Cloudy skies throughout the day with afternoon...               rain   
668                  Partly cloudy throughout the day.  partly-cloudy-day   

                                              stations  
0    D9186,KHSV,72323003856,STAA1,KDCU,72227953852,...  
1    F2925,D9186,KHSV,D2741,72323003856,KDCU,STAA1,...  
2    D9186,KHSV,72323003856,STAA1,KHUA,72030763804,...  
3    D9186,KHSV,72323003856,KDCU,STAA1,KHUA,7222795...  
4    D9186,KHSV,72323003856,STAA1,KHUA,72030763804,...  
..                                                 ...  
664  D9186,KHSV,72323003856,KDCU,72227953852,720307...  
665  D9186,KHSV,72323003856,KDCU,72227953852,720307...  
666                D9186,KHSV,KDCU,KHUA,KMDQ,KCMD,K8A0  
667        

In [3]:
dataset.columns

Index(['Site Id', 'Date', 'SM_2', 'SM_4', 'SM_8', 'SM_20', 'SM_40', 'ST_2',
       'ST_4', 'ST_8', 'ST_20', 'ST_40', 'tempmax', 'tempmin', 'temp',
       'feelslikemax', 'feelslikemin', 'feelslike', 'dew', 'humidity',
       'precip', 'precipprob', 'precipcover', 'preciptype', 'snow',
       'snowdepth', 'windgust', 'windspeed', 'winddir', 'sealevelpressure',
       'cloudcover', 'visibility', 'solarradiation', 'solarenergy', 'uvindex',
       'severerisk', 'sunrise', 'sunset', 'moonphase', 'conditions',
       'description', 'icon', 'stations'],
      dtype='object')

In [4]:
dataset.drop(
    [
        "Site Id",
        "Date",
        "SM_4",
        "SM_8",
        "SM_20",
        "SM_40",
        "ST_4",
        "ST_8",
        "ST_20",
        "ST_40",
        "feelslikemax",
        "feelslikemin",
        "feelslike",
        "solarenergy",
        "precipprob",
        "precipcover",
        "preciptype",
        "snow",
        "snowdepth",
        "windgust",
        "winddir",
        "sealevelpressure",
        "visibility",
        "solarenergy",
        "uvindex",
        "severerisk",
        "sunrise",
        "sunset",
        "moonphase",
        "description",
        "icon",
        "stations",
    ], inplace=True,axis=1
)

In [5]:
dataset

SM_2  ST_2  tempmax  tempmin  temp   dew  humidity  precip  windspeed  \
0    38.2  15.9     26.1     14.3  21.2  17.7      81.4  54.452       40.4   
1    41.7  15.7     14.4     -0.2   9.9   9.3      96.3  12.945       25.2   
2    40.8  11.8      0.0     -3.4  -1.0  -3.0      86.9   3.248       28.5   
3    40.4   9.3      9.6     -4.3   2.2  -0.1      85.3   0.000       22.0   
4    41.6   7.3     12.3      2.9   6.7   4.3      85.9   0.000       13.9   
..    ...   ...      ...      ...   ...   ...       ...     ...        ...   
664  18.0  18.8     27.6     17.2  22.0  14.9      65.5   0.000       14.5   
665  18.2  19.2     28.6     15.0  21.8  14.3      65.3   0.000       14.8   
666  18.4  20.0     28.2     15.2  21.3  14.0      64.9   0.000       19.5   
667  18.0  19.0     21.2      7.0  12.7   9.7      82.4   0.906       25.0   
668  16.6  14.2     12.8      3.4   7.4  -0.8      59.3   0.000       29.5   

     cloudcover  solarradiation              conditions  
0          88.5            67.6  Rain, Partially cloudy  
1         100.0            20.9    Snow, Rain, Overcast  
2          91.1            10.3    Snow, Rain, Overcast  
3          19.3           114.3                   Clear  
4          48.9            50.9        Partially cloudy  
..          ...             ...                     ...  
664        56.0            93.0        Partially cloudy  
665        40.3           107.5        Partially cloudy  
666        33.0           106.1        Partially cloudy  
667        93.2            21.3          Rain, Overcast  
668        41.0           156.5        Partially cloudy  

[669 rows x 12 columns]

In [6]:
dataset.columns

Index(['SM_2', 'ST_2', 'tempmax', 'tempmin', 'temp', 'dew', 'humidity',
       'precip', 'windspeed', 'cloudcover', 'solarradiation', 'conditions'],
      dtype='object')

In [7]:
set(dataset.conditions).__len__()

12

In [8]:
X_train=dataset.iloc[:,1:].values
X_train

array([[15.9, 26.1, 14.3, ..., 88.5, 67.6, 'Rain, Partially cloudy'],
       [15.7, 14.4, -0.2, ..., 100.0, 20.9, 'Snow, Rain, Overcast'],
       [11.8, 0.0, -3.4, ..., 91.1, 10.3, 'Snow, Rain, Overcast'],
       ...,
       [20.0, 28.2, 15.2, ..., 33.0, 106.1, 'Partially cloudy'],
       [19.0, 21.2, 7.0, ..., 93.2, 21.3, 'Rain, Overcast'],
       [14.2, 12.8, 3.4, ..., 41.0, 156.5, 'Partially cloudy']],
      dtype=object)

In [9]:
y_train=dataset.iloc[:,0].values
y_train

array([38.2, 41.7, 40.8, 40.4, 41.6, 37.8, 37.9, 36.6, 36.1, 39.2, 37. ,
       36.4, 36. , 34.8, 34.2, 40.8, 38.9, 36.7, 36.4, 40.9, 36.6, 35.7,
       35. , 34.8, 34.5, 34. , 33.6, 33.4, 32.8, 32.4, 32. , 31.8, 31.4,
       39.1, 38.3, 36.3, 35.2, 34.7, 34.4, 34. , 33.4, 33. , 32.4, 31.6,
       30.7, 30. , 29.1, 27.9, 37.5, 35.2, 34.2, 33.6, 38.8, 46. , 39.4,
       40.3, 37.1, 41.3, 37.6, 36.4, 35.4, 34.6, 33.6, 32.2, 30. , 27.4,
       38.1, 43.8, 37.2, 35.8, 34.7, 37.7, 36.2, 35.3, 40.4, 38.2, 37.3,
       38.8, 36.8, 35.7, 34.2, 47.2, 38. , 35.9, 34.8, 32.7, 31.1, 28.9,
       27.2, 40.9, 36.8, 34.8, 33.6, 31.4, 28.8, 37.9, 36.3, 33.6, 32.2,
       29.6, 27.1, 27.1, 27.4, 41.8, 37.4, 34.4, 38.5, 37.3, 35.4, 33.2,
       30. , 27.5, 25.5, 23.9, 23. , 22.9, 23. , 22.4, 21.8, 21.5, 21.5,
       21. , 20.8, 20.6, 20.4, 35.3, 31.3, 30.1, 26.6, 23.6, 22. , 21.3,
       20.5, 19.8, 19.7, 19.6, 18.9, 18.7, 18.6, 18.7, 18.5, 18.5, 21.1,
       31.6, 34.6, 35.5, 36.7, 35.1, 32.8, 29. , 25

In [10]:
""" taking care of categorical data in conditions column """
from sklearn.compose import  ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [10])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_train

array([[0.0, 0.0, 0.0, ..., 40.4, 88.5, 67.6],
       [0.0, 0.0, 0.0, ..., 25.2, 100.0, 20.9],
       [0.0, 0.0, 0.0, ..., 28.5, 91.1, 10.3],
       ...,
       [0.0, 0.0, 1.0, ..., 19.5, 33.0, 106.1],
       [0.0, 0.0, 0.0, ..., 25.0, 93.2, 21.3],
       [0.0, 0.0, 1.0, ..., 29.5, 41.0, 156.5]], dtype=object)

In [11]:
X_train.shape

(669, 22)

In [12]:
y_train.shape

(669,)

In [13]:
X_train[0]

array([0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 15.9,
       26.1, 14.3, 21.2, 17.7, 81.4, 54.452, 40.4, 88.5, 67.6],
      dtype=object)

In [14]:
""" Standard Scaling data """
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,12:]=sc.fit_transform(X_train[:,12:])
X_train[0]

array([0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       -0.1571235233007997, 0.31665818694276976, 0.2625685518961803,
       0.45383440656593865, 0.6781568392232719, 0.7864012245095118,
       7.33659801262699, 2.9565871757618005, 1.4393208188588396,
       -1.2116323664367021], dtype=object)

In [15]:
X_train[0].shape

(22,)

In [16]:
""" Model """
model=keras.Sequential(
    [
        keras.layers.Dense(22,activation=keras.activations.relu),
        keras.layers.Dense(44,activation=keras.activations.relu),
        keras.layers.Dense(1)
    ]
)

In [17]:
model.compile(optimizer=keras.optimizers.Adam(),loss=keras.losses.mean_squared_error,metrics=keras.metrics.Accuracy())

In [19]:
X_train=np.asarray(X_train).astype("float32")
y_train=np.asarray(y_train).astype("float32")

In [22]:
model.fit(X_train,y_train,epochs=50)

Epoch 1/50
 1/21 [>.............................] - ETA: 0s - loss: 27.2489 - accuracy: 0.0000e+00

21/21 [==============================] - 0s 2ms/step - loss: 28.2344 - accuracy: 0.0000e+00
Epoch 2/50
21/21 [==============================] - 0s 2ms/step - loss: 27.7723 - accuracy: 0.0000e+00
Epoch 3/50
21/21 [==============================] - 0s 2ms/step - loss: 27.6534 - accuracy: 0.0000e+00
Epoch 4/50
21/21 [==============================] - 0s 2ms/step - loss: 27.3279 - accuracy: 0.0000e+00
Epoch 5/50
21/21 [==============================] - 0s 2ms/step - loss: 27.1644 - accuracy: 0.0000e+00
Epoch 6/50
21/21 [==============================] - 0s 2ms/step - loss: 26.9007 - accuracy: 0.0000e+00
Epoch 7/50
21/21 [==============================] - 0s 3ms/step - loss: 26.7668 - accuracy: 0.0000e+00
Epoch 8/50
21/21 [==============================] - 0s 2ms/step - loss: 26.5376 - accuracy: 0.0000e+00
Epoch 9/50
21/21 [==============================] - 0s 2ms/step - loss: 26.4579 - accuracy: 0.0000e+00
Epoch 10/50
21/21 [==============================] - 0s 2ms/step - loss: 26.2465 - a

In [26]:
y_pred=model.predict(X_train).reshape(-1,1)
y_pred

21/21 [==============================] - 0s 1ms/step


array([[39.670784],
       [33.995834],
       [38.60034 ],
       [34.621887],
       [37.46425 ],
       [38.151367],
       [35.03679 ],
       [31.921083],
       [37.416817],
       [33.083405],
       [33.926582],
       [33.26864 ],
       [33.48154 ],
       [35.16532 ],
       [34.593925],
       [42.339256],
       [39.94062 ],
       [35.47549 ],
       [30.554962],
       [39.458443],
       [41.382618],
       [37.97622 ],
       [36.574394],
       [35.224632],
       [35.458725],
       [37.20319 ],
       [35.12729 ],
       [38.8952  ],
       [38.975685],
       [35.879997],
       [31.796045],
       [35.23626 ],
       [35.431957],
       [40.38289 ],
       [39.99972 ],
       [37.3879  ],
       [35.19902 ],
       [34.13517 ],
       [33.788544],
       [34.862167],
       [32.41069 ],
       [33.374687],
       [33.85302 ],
       [34.03744 ],
       [33.612602],
       [33.50337 ],
       [34.765385],
       [38.337326],
       [33.73801 ],
       [32.96274 ],


In [28]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_train,y_pred)

3.9268508

In [33]:
X_train.shape

(669, 22)

In [36]:
model.input_shape

(None, 22)

In [37]:
to_predit=X_train[0].reshape(-1,22)

In [38]:
model.predict(to_predit)

1/1 [==============================] - 0s 25ms/step


array([[39.670784]], dtype=float32)

In [39]:
y_train[0]

38.2